# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thermostat.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.btnHome = QtWidgets.QPushButton(self.centralwidget)
        self.btnHome.setGeometry(QtCore.QRect(0, 0, 200, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHome.sizePolicy().hasHeightForWidth())
        self.btnHome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btnHome.setFont(font)
        self.btnHome.setObjectName("btnHome")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 50, 800, 430))
        self.stackedWidget.setObjectName("stackedWidget")
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setAutoFillBackground(True)
        self.HomePage.setObjectName("HomePage")
        self.btnPlusTemp = QtWidgets.QPushButton(self.HomePage)
        self.btnPlusTemp.setGeometry(QtCore.QRect(680, 80, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.btnPlusTemp.setFont(font)
        self.btnPlusTemp.setObjectName("btnPlusTemp")
        self.btnMinusTemp = QtWidgets.QPushButton(self.HomePage)
        self.btnMinusTemp.setGeometry(QtCore.QRect(680, 250, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(27)
        self.btnMinusTemp.setFont(font)
        self.btnMinusTemp.setObjectName("btnMinusTemp")
        self.labTimeHP = QtWidgets.QLabel(self.HomePage)
        self.labTimeHP.setGeometry(QtCore.QRect(60, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labTimeHP.setFont(font)
        self.labTimeHP.setAlignment(QtCore.Qt.AlignCenter)
        self.labTimeHP.setObjectName("labTimeHP")
        self.labOutdoor = QtWidgets.QLabel(self.HomePage)
        self.labOutdoor.setGeometry(QtCore.QRect(40, 130, 101, 17))
        self.labOutdoor.setAlignment(QtCore.Qt.AlignCenter)
        self.labOutdoor.setObjectName("labOutdoor")
        self.LabOutTemp = QtWidgets.QLabel(self.HomePage)
        self.LabOutTemp.setGeometry(QtCore.QRect(10, 160, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(63)
        font.setBold(True)
        font.setWeight(75)
        self.LabOutTemp.setFont(font)
        self.LabOutTemp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LabOutTemp.setObjectName("LabOutTemp")
        self.labOutHumid = QtWidgets.QLabel(self.HomePage)
        self.labOutHumid.setGeometry(QtCore.QRect(40, 270, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labOutHumid.setFont(font)
        self.labOutHumid.setAlignment(QtCore.Qt.AlignCenter)
        self.labOutHumid.setObjectName("labOutHumid")
        self.labModeDispHP = QtWidgets.QLabel(self.HomePage)
        self.labModeDispHP.setGeometry(QtCore.QRect(50, 340, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labModeDispHP.setFont(font)
        self.labModeDispHP.setAlignment(QtCore.Qt.AlignCenter)
        self.labModeDispHP.setObjectName("labModeDispHP")
        self.labIndoor = QtWidgets.QLabel(self.HomePage)
        self.labIndoor.setGeometry(QtCore.QRect(360, 71, 67, 17))
        self.labIndoor.setAlignment(QtCore.Qt.AlignCenter)
        self.labIndoor.setObjectName("labIndoor")
        self.labIndoorTemp = QtWidgets.QLabel(self.HomePage)
        self.labIndoorTemp.setGeometry(QtCore.QRect(310, 90, 181, 151))
        font = QtGui.QFont()
        font.setPointSize(110)
        font.setBold(True)
        font.setWeight(75)
        self.labIndoorTemp.setFont(font)
        self.labIndoorTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labIndoorTemp.setObjectName("labIndoorTemp")
        self.labInHumid = QtWidgets.QLabel(self.HomePage)
        self.labInHumid.setGeometry(QtCore.QRect(340, 300, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labInHumid.setFont(font)
        self.labInHumid.setAlignment(QtCore.Qt.AlignCenter)
        self.labInHumid.setObjectName("labInHumid")
        self.labScheduleDisp = QtWidgets.QLabel(self.HomePage)
        self.labScheduleDisp.setGeometry(QtCore.QRect(290, 360, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labScheduleDisp.setFont(font)
        self.labScheduleDisp.setAlignment(QtCore.Qt.AlignCenter)
        self.labScheduleDisp.setObjectName("labScheduleDisp")
        self.labSetTemp = QtWidgets.QLabel(self.HomePage)
        self.labSetTemp.setGeometry(QtCore.QRect(650, 160, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(63)
        font.setBold(True)
        font.setWeight(75)
        self.labSetTemp.setFont(font)
        self.labSetTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.labSetTemp.setObjectName("labSetTemp")
        self.labSetTo = QtWidgets.QLabel(self.HomePage)
        self.labSetTo.setGeometry(QtCore.QRect(670, 140, 67, 17))
        self.labSetTo.setAlignment(QtCore.Qt.AlignCenter)
        self.labSetTo.setObjectName("labSetTo")
        self.labDegrees1 = QtWidgets.QLabel(self.HomePage)
        self.labDegrees1.setGeometry(QtCore.QRect(140, 150, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labDegrees1.setFont(font)
        self.labDegrees1.setAlignment(QtCore.Qt.AlignCenter)
        self.labDegrees1.setObjectName("labDegrees1")
        self.labDegrees2 = QtWidgets.QLabel(self.HomePage)
        self.labDegrees2.setGeometry(QtCore.QRect(480, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.labDegrees2.setFont(font)
        self.labDegrees2.setAlignment(QtCore.Qt.AlignCenter)
        self.labDegrees2.setObjectName("labDegrees2")
        self.labDegrees3 = QtWidgets.QLabel(self.HomePage)
        self.labDegrees3.setGeometry(QtCore.QRect(750, 150, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labDegrees3.setFont(font)
        self.labDegrees3.setAlignment(QtCore.Qt.AlignCenter)
        self.labDegrees3.setObjectName("labDegrees3")
        self.stackedWidget.addWidget(self.HomePage)
        self.FanPage = QtWidgets.QWidget()
        self.FanPage.setObjectName("FanPage")
        self.labStatusFP = QtWidgets.QLabel(self.FanPage)
        self.labStatusFP.setGeometry(QtCore.QRect(60, 310, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labStatusFP.setFont(font)
        self.labStatusFP.setAlignment(QtCore.Qt.AlignCenter)
        self.labStatusFP.setObjectName("labStatusFP")
        self.labModeDispFP = QtWidgets.QLabel(self.FanPage)
        self.labModeDispFP.setGeometry(QtCore.QRect(60, 350, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labModeDispFP.setFont(font)
        self.labModeDispFP.setAlignment(QtCore.Qt.AlignCenter)
        self.labModeDispFP.setObjectName("labModeDispFP")
        self.btnDoneFP = QtWidgets.QPushButton(self.FanPage)
        self.btnDoneFP.setGeometry(QtCore.QRect(40, 50, 121, 61))
        self.btnDoneFP.setObjectName("btnDoneFP")
        self.btnHelpFP = QtWidgets.QPushButton(self.FanPage)
        self.btnHelpFP.setGeometry(QtCore.QRect(40, 140, 121, 61))
        self.btnHelpFP.setObjectName("btnHelpFP")
        self.btnFanOn = QtWidgets.QPushButton(self.FanPage)
        self.btnFanOn.setGeometry(QtCore.QRect(260, 50, 301, 81))
        self.btnFanOn.setObjectName("btnFanOn")
        self.btnFanAuto = QtWidgets.QPushButton(self.FanPage)
        self.btnFanAuto.setGeometry(QtCore.QRect(260, 130, 301, 81))
        self.btnFanAuto.setObjectName("btnFanAuto")
        self.btnFanCirculate = QtWidgets.QPushButton(self.FanPage)
        self.btnFanCirculate.setGeometry(QtCore.QRect(260, 210, 301, 81))
        self.btnFanCirculate.setObjectName("btnFanCirculate")
        self.stackedWidget.addWidget(self.FanPage)
        self.ModePage = QtWidgets.QWidget()
        self.ModePage.setObjectName("ModePage")
        self.labStatusMP = QtWidgets.QLabel(self.ModePage)
        self.labStatusMP.setGeometry(QtCore.QRect(60, 350, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labStatusMP.setFont(font)
        self.labStatusMP.setAlignment(QtCore.Qt.AlignCenter)
        self.labStatusMP.setObjectName("labStatusMP")
        self.btnHelpMP = QtWidgets.QPushButton(self.ModePage)
        self.btnHelpMP.setGeometry(QtCore.QRect(40, 140, 121, 61))
        self.btnHelpMP.setObjectName("btnHelpMP")
        self.labModeDispMP = QtWidgets.QLabel(self.ModePage)
        self.labModeDispMP.setGeometry(QtCore.QRect(60, 310, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labModeDispMP.setFont(font)
        self.labModeDispMP.setAlignment(QtCore.Qt.AlignCenter)
        self.labModeDispMP.setObjectName("labModeDispMP")
        self.btnDoneMP = QtWidgets.QPushButton(self.ModePage)
        self.btnDoneMP.setGeometry(QtCore.QRect(40, 50, 121, 61))
        self.btnDoneMP.setObjectName("btnDoneMP")
        self.btnModeOff = QtWidgets.QPushButton(self.ModePage)
        self.btnModeOff.setGeometry(QtCore.QRect(260, 210, 301, 81))
        self.btnModeOff.setObjectName("btnModeOff")
        self.btnModeCool = QtWidgets.QPushButton(self.ModePage)
        self.btnModeCool.setGeometry(QtCore.QRect(260, 130, 301, 81))
        self.btnModeCool.setObjectName("btnModeCool")
        self.btnModeHeat = QtWidgets.QPushButton(self.ModePage)
        self.btnModeHeat.setGeometry(QtCore.QRect(260, 50, 301, 81))
        self.btnModeHeat.setObjectName("btnModeHeat")
        self.stackedWidget.addWidget(self.ModePage)
        self.SettingsPage = QtWidgets.QWidget()
        self.SettingsPage.setObjectName("SettingsPage")
        self.labDateSP = QtWidgets.QLabel(self.SettingsPage)
        self.labDateSP.setGeometry(QtCore.QRect(20, 170, 161, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labDateSP.setFont(font)
        self.labDateSP.setObjectName("labDateSP")
        self.labTimeSP = QtWidgets.QLabel(self.SettingsPage)
        self.labTimeSP.setGeometry(QtCore.QRect(50, 210, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.labTimeSP.setFont(font)
        self.labTimeSP.setObjectName("labTimeSP")
        self.scrollArea = QtWidgets.QScrollArea(self.SettingsPage)
        self.scrollArea.setGeometry(QtCore.QRect(249, 49, 311, 301))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 297, 301))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(0, 0, 302, 388))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnEditSched = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditSched.sizePolicy().hasHeightForWidth())
        self.btnEditSched.setSizePolicy(sizePolicy)
        self.btnEditSched.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnEditSched.setFont(font)
        self.btnEditSched.setObjectName("btnEditSched")
        self.verticalLayout.addWidget(self.btnEditSched)
        self.btnViewSched = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnViewSched.sizePolicy().hasHeightForWidth())
        self.btnViewSched.setSizePolicy(sizePolicy)
        self.btnViewSched.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnViewSched.setFont(font)
        self.btnViewSched.setObjectName("btnViewSched")
        self.verticalLayout.addWidget(self.btnViewSched)
        self.btnWeather = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWeather.sizePolicy().hasHeightForWidth())
        self.btnWeather.setSizePolicy(sizePolicy)
        self.btnWeather.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnWeather.setFont(font)
        self.btnWeather.setObjectName("btnWeather")
        self.verticalLayout.addWidget(self.btnWeather)
        self.btnColorThemes = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnColorThemes.sizePolicy().hasHeightForWidth())
        self.btnColorThemes.setSizePolicy(sizePolicy)
        self.btnColorThemes.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnColorThemes.setFont(font)
        self.btnColorThemes.setObjectName("btnColorThemes")
        self.verticalLayout.addWidget(self.btnColorThemes)
        self.btnUnits = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUnits.sizePolicy().hasHeightForWidth())
        self.btnUnits.setSizePolicy(sizePolicy)
        self.btnUnits.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnUnits.setFont(font)
        self.btnUnits.setObjectName("btnUnits")
        self.verticalLayout.addWidget(self.btnUnits)
        self.btnTest = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTest.sizePolicy().hasHeightForWidth())
        self.btnTest.setSizePolicy(sizePolicy)
        self.btnTest.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnTest.setFont(font)
        self.btnTest.setObjectName("btnTest")
        self.verticalLayout.addWidget(self.btnTest)
        self.btnVacationMode = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnVacationMode.sizePolicy().hasHeightForWidth())
        self.btnVacationMode.setSizePolicy(sizePolicy)
        self.btnVacationMode.setMinimumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnVacationMode.setFont(font)
        self.btnVacationMode.setObjectName("btnVacationMode")
        self.verticalLayout.addWidget(self.btnVacationMode)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.btnClose = QtWidgets.QPushButton(self.SettingsPage)
        self.btnClose.setGeometry(QtCore.QRect(630, 280, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnClose.setFont(font)
        self.btnClose.setObjectName("btnClose")
        self.stackedWidget.addWidget(self.SettingsPage)
        self.btnFan = QtWidgets.QPushButton(self.centralwidget)
        self.btnFan.setGeometry(QtCore.QRect(200, 0, 200, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFan.sizePolicy().hasHeightForWidth())
        self.btnFan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btnFan.setFont(font)
        self.btnFan.setObjectName("btnFan")
        self.btnMode = QtWidgets.QPushButton(self.centralwidget)
        self.btnMode.setGeometry(QtCore.QRect(400, 0, 200, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMode.sizePolicy().hasHeightForWidth())
        self.btnMode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btnMode.setFont(font)
        self.btnMode.setObjectName("btnMode")
        self.btnSettings = QtWidgets.QPushButton(self.centralwidget)
        self.btnSettings.setGeometry(QtCore.QRect(600, 0, 200, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSettings.sizePolicy().hasHeightForWidth())
        self.btnSettings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btnSettings.setFont(font)
        self.btnSettings.setObjectName("btnSettings")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnHome.setText(_translate("MainWindow", "Home"))
        self.btnPlusTemp.setText(_translate("MainWindow", "+"))
        self.btnMinusTemp.setText(_translate("MainWindow", "-"))
        self.labTimeHP.setText(_translate("MainWindow", "3:17pm"))
        self.labOutdoor.setText(_translate("MainWindow", "OUTDOOR"))
        self.LabOutTemp.setText(_translate("MainWindow", "91"))
        self.labOutHumid.setText(_translate("MainWindow", "57% Humidity"))
        self.labModeDispHP.setText(_translate("MainWindow", "cool on"))
        self.labIndoor.setText(_translate("MainWindow", "INDOOR"))
        self.labIndoorTemp.setText(_translate("MainWindow", "78"))
        self.labInHumid.setText(_translate("MainWindow", "53% Humidity"))
        self.labScheduleDisp.setText(_translate("MainWindow", "HOLD UNTIL 6:00pm"))
        self.labSetTemp.setText(_translate("MainWindow", "76"))
        self.labSetTo.setText(_translate("MainWindow", "SET TO"))
        self.labDegrees1.setText(_translate("MainWindow", "o"))
        self.labDegrees2.setText(_translate("MainWindow", "o"))
        self.labDegrees3.setText(_translate("MainWindow", "o"))
        self.labStatusFP.setText(_translate("MainWindow", "STATUS:"))
        self.labModeDispFP.setText(_translate("MainWindow", "Fan on"))
        self.btnDoneFP.setText(_translate("MainWindow", "Done"))
        self.btnHelpFP.setText(_translate("MainWindow", "Help"))
        self.btnFanOn.setText(_translate("MainWindow", "On"))
        self.btnFanAuto.setText(_translate("MainWindow", "Automatic"))
        self.btnFanCirculate.setText(_translate("MainWindow", "Circulate"))
        self.labStatusMP.setText(_translate("MainWindow", "Fan on"))
        self.btnHelpMP.setText(_translate("MainWindow", "Help"))
        self.labModeDispMP.setText(_translate("MainWindow", "STATUS:"))
        self.btnDoneMP.setText(_translate("MainWindow", "Done"))
        self.btnModeOff.setText(_translate("MainWindow", "Off"))
        self.btnModeCool.setText(_translate("MainWindow", "Cool"))
        self.btnModeHeat.setText(_translate("MainWindow", "Heat"))
        self.labDateSP.setText(_translate("MainWindow", "Wednesday, Jun 27"))
        self.labTimeSP.setText(_translate("MainWindow", "3:17pm"))
        self.btnEditSched.setText(_translate("MainWindow", "Create/Edit Schedule"))
        self.btnViewSched.setText(_translate("MainWindow", "View Schedule Summary"))
        self.btnWeather.setText(_translate("MainWindow", "Weather"))
        self.btnColorThemes.setText(_translate("MainWindow", "Color Themes"))
        self.btnUnits.setText(_translate("MainWindow", "Temperature Units"))
        self.btnTest.setText(_translate("MainWindow", "Vacation Mode"))
        self.btnVacationMode.setText(_translate("MainWindow", "Vacation Mode"))
        self.btnClose.setText(_translate("MainWindow", "Close"))
        self.btnFan.setText(_translate("MainWindow", "Fan"))
        self.btnMode.setText(_translate("MainWindow", "Mode"))
        self.btnSettings.setText(_translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

